package com.rrmadon.flashsale.reservation;

import java.time.Duration;
import java.util.UUID;

/**
 * Atomically claims one unit of stock for a SKU. The whole correctness
 * guarantee of this project lives here: a single Redis Lua script does the
 * check-and-decrement as one indivisible step, so two concurrent callers can
 * never both see the same "1 left" and both proceed.
 *
 * See the architecture doc §05 for the full reasoning, including why the
 * reservation token is generated by the caller (this class), not inside the
 * script.
 */
public interface ReservationStore {

    /**
     * Attempts to claim one unit of stock for {@code sku}.
     *
     * @param sku the SKU's stock key name, e.g. "sku123"
     * @param ttl how long the reservation hold survives before it must be
     *            renewed (by completing checkout) or is released back to
     *            the pool
     * @return the outcome; only {@code allowed() == true} means a unit was
     *         actually reserved
     */
    ClaimResult claim(String sku, Duration ttl);

    /**
     * Releases a held reservation early — e.g. checkout failed in a way
     * that should not hold the unit until the TTL naturally expires.
     *
     * @param reservationToken the token returned by a successful claim
     */
    void release(String reservationToken);

    /** Generates a fresh, unguessable reservation token. Not from Lua — see the class doc. */
    static String newToken() {
        return UUID.randomUUID().toString();
    }
}
