-- KEYS[1] = stock key, e.g. "stock:sku123"
-- KEYS[2] = the pending-reservations sorted set, "reservations:pending"
-- ARGV[1] = reservation TTL in seconds
-- ARGV[2] = reservation token, generated by the caller (a real CSPRNG) before
--           this script runs -- never generated in Lua. Redis's Lua
--           environment is deliberately deterministic for replication, so
--           it is not a safe source of an unguessable token.
-- ARGV[3] = sku (plain string, for the ZADD member)
-- ARGV[4] = now, unix seconds (supplied by the caller so expiry math is
--           testable against an injected Clock, not Redis's own timer)

local remaining = tonumber(redis.call('GET', KEYS[1]))

if remaining == nil or remaining <= 0 then
  return {0, 0}
end

redis.call('DECR', KEYS[1])
local expiresAt = tonumber(ARGV[4]) + tonumber(ARGV[1])
redis.call('ZADD', KEYS[2], expiresAt, ARGV[3] .. ':' .. ARGV[2])

return {1, remaining - 1, ARGV[2]}
