-- KEYS[1] = stock key, e.g. "stock:sku123"
-- ARGV[1] = reservation TTL in seconds
-- ARGV[2] = reservation token, generated by the caller (a real CSPRNG) before
--           this script runs -- never generated in Lua. Redis's Lua
--           environment is deliberately deterministic for replication, so
--           it is not a safe source of an unguessable token, and INCR-based
--           sequential IDs are directly enumerable/guessable either way.

local remaining = tonumber(redis.call('GET', KEYS[1]))

if remaining == nil or remaining <= 0 then
  return {0, 0}
end

redis.call('DECR', KEYS[1])
redis.call('SETEX', 'reservation:' .. ARGV[2], tonumber(ARGV[1]), 'held')

return {1, remaining - 1, ARGV[2]}
